# Generated by Django 6.0 on 2025-12-21 00:04

import celebration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                (
                    "household_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional grouping label to seat families together.",
                        max_length=160,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bride", "Bride"),
                            ("groom", "Groom"),
                            ("family", "Family"),
                        ],
                        max_length=24,
                    ),
                ),
                ("relationship", models.CharField(blank=True, max_length=120)),
                ("invited", models.BooleanField(default=True)),
                (
                    "verified",
                    models.BooleanField(
                        default=True,
                        help_text="Unverified guests were not part of the original list but submitted an RSVP.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["full_name"],
                "unique_together": {("full_name", "email")},
            },
        ),
        migrations.CreateModel(
            name="PhotoSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "image",
                    models.ImageField(upload_to=celebration.models.upload_to_photo),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="celebration.guest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attending", models.BooleanField()),
                ("party_size", models.PositiveIntegerField(default=1)),
                ("email", models.EmailField(max_length=254)),
                (
                    "meal_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chef", "Chef's Seasonal Selection"),
                            ("chicken", "Herb-Roasted Chicken"),
                            ("fish", "Citrus Sea Bass"),
                            ("veggie", "Garden Risotto"),
                        ],
                        max_length=32,
                    ),
                ),
                ("song_request", models.CharField(blank=True, max_length=160)),
                ("message", models.TextField(blank=True)),
                (
                    "avatar_config",
                    models.JSONField(default=celebration.models.default_avatar_config),
                ),
                ("livestream_requested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="celebration.guest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
