# Generated by Django 6.0.2 on 2026-02-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celebration", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="guest",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
