# Generated by Django 4.2.29 on 2026-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration', '0002_make_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='guest_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
